import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header';
import CreateProduct from '@/components/Create';
import { useDispatch } from 'react-redux';
import connectionDb from '@/utils/db';
import { getAllProducts } from '@/actions/ProductAction';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   const dispatch = useDispatch();
   connectionDb();
   dispatch(getAllProducts());
  return (
    <>
      <Head>
        <title>Asikur Personal Portfolio & Blog Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>

      <Header />
      <Link href="/components/Create">
        {/* <CreateProduct /> */}
        Hi
      </Link>
    </>
  );
}
